apiVersion: v1
kind: Pod
metadata:
 name: demoapp
 labels:
 name: demoapp
spec:
 containers:
 - name: demoimage
 image: idowuilekura/teleport_demo
 resources:
 limits:
 memory: "128Mi"
 cpu: "500m"
 ports:
 - containerPort: 5000
